### ISSUE TITLE
Elements with the http namespace are not recognized

### ISSUE THREAD

**Issue by jbenhamou** [machaval/mule-intellij-plugins#92]
The IntelliJ Mule editor does not recognize elements with the **http namespace**
---
<img width="1259" alt="skitch" src="https://cloud.githubusercontent.com/assets/4597679/26272396/f4fc8236-3ccb-11e7-840c-c78fba6efeac.png">

**Comment by tipt** [comment]
I had this problem too, I fixed it by mapping the URI for the schema to a local file.  Open Settings > Languages & Frameworks > Schemas & DTDs, then add a new entry in "External Schemas and DTDs".  Map the URI to the local location for the "mule-httpn.xsd"

![image](https://user-images.githubusercontent.com/6667816/28690156-2b5760e4-72e6-11e7-8ee5-01dccba74ca6.png)

**Comment by javaduke** [comment]
The schema handling has been improved in the latest release, it is still not ideal, but better :)
